### PR TITLE
GetDeploymentStatus support replica count greater than one

### PR DESCRIPTION
**Pull request by tjololo**
Update GetDeploymentStatus to check against .Status.Replicas

Check against UpdatedReplicas instead of AvailableReplicas

### CODE REVIEW

**Comment by sabre1041** [comment]
@tjololo thank you for this enhancement! However, would you be able to return the check against the `availableReplicas` instead of `updatedReplicas` as it will take the `minReadySeconds` value into consideration?

**Comment by tjololo** [comment]
> @tjololo thank you for this enhancement! However, would you be able to return the check against the `availableReplicas` instead of `updatedReplicas` as it will take the `minReadySeconds` value into consideration?

Sure, made the changes

**Review by sabre1041 — APPROVED** [review]
LGTM. Thanks!

**Comment by arve0** [comment]
@sabre1041 Any plans to release this to the stable channel?

**Pull request merged**
