### PR TITLE
Migrated directly modifying SCC's and use RBAC instead

### PR DESCRIPTION
**Pull request by sabre1041**
Removed directly modifying the anyuid SCC and removed the finalizer as it is no longer needed

Resolves #212

### CODE REVIEW

**Comment by thomasmckay** [comment]
Will these changes _only_ work with OCP-4.5? Is it possible to if/else around things to maintain backward compatible?

**Comment by sabre1041** [comment]
@thomasmckay functionality is currently available in OCP 4.3/4.4 (as well as potentially older releases)

**Comment by kurtismullins** [comment]
@sabre1041 It looks like this PR may need a rebase.

**Comment by sabre1041** [comment]
@kurtismullins done.

A new task must be added to the quay-docs side to remove the finalizer discussion

**Review by alecmerdler — APPROVED** [review]

**Pull request merged**
