### PR TITLE
pgupgrade: reverting postgresql version to 13 for quay (PROJQUAY-7253)

### PR DESCRIPTION
**Pull request by deshpandevlab**
This reverts the quay pg upgrade changes in commit 673eff30cc03e590539fca12bc2b1721d68ff4f1

Refer https://github.com/quay/quay-operator/pull/959#issuecomment-2364286444 for details. 

### Testing

- Tested push-pull 
- Ran e2e test

### PG versions queried on quay and clair pods

Quay PG pod:
```
Found PostgreSQL pod: shudeshp-registry-quay-database-64cb6b96bb-x6vfq
Pod is ready. Executing version query...
                                                    version
---------------------------------------------------------------------------------------------------------------
 PostgreSQL 13.11 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), 64-bit
 ```

Clair PG pod: 
 ```
 Found PostgreSQL pod: shudeshp-registry-clair-postgres-6b7c7c48cd-rrbld
Pod is ready. Executing version query...
                                                   version
--------------------------------------------------------------------------------------------------------------
 PostgreSQL 15.8 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-2), 64-bit
 ```

- validated that the security scan is passed for the tags with this change
Screenshot 2024-09-24 at 10 20 13 PM

### CODE REVIEW

**Comment by deshpandevlab** [comment]
The tests are failing for timeouts while getting waiting for quay to get ready. Checking if the test environment is changed. Did not notice any error while deploying locally:
https://shudeshp-registry-quay-quay-enterprise.apps.jonathan-ocp.gcp.quaydev.org/

thanks @bcaton85 for the help with pod logs. The test env needs to be updated to accommodate clair settings

**Review by bcaton85 — APPROVED** [review]

**Review by jonathankingfc — APPROVED** [review]
LGTM

**Pull request merged**
