### PR TITLE
csv: proxy-aware/fips annotation (PROJQUAY-3709)

### PR DESCRIPTION
**Pull request by ricardomaraschini**
Add proxy-aware and fips in the list of infrastructure features.

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
@HammerMeetNail we don't need to manually port this to midstream anymore, right ?

**Comment by HammerMeetNail** [comment]
> @HammerMeetNail we don't need to manually port this to midstream anymore, right ?

Right, it's all done automatically now.

**Review by HammerMeetNail — APPROVED** [review]
LGTM

**Pull request merged**
