### PR TITLE
Update a deprecated Local Development command in readme.md

### PR DESCRIPTION
**Pull request by drichtarik**
@sabre1041 deprecated command.
see the change log here: https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#changed-3 and here: https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#changed-3

### CODE REVIEW

**Comment by thomasmckay** [comment]
Thanks for this! We are moving the docs to https://github.com/quay/quay-docs/blob/master/modules/proc_deploy-quay-openshift-operator.adoc so please make PR there.

https://github.com/redhat-cop/quay-operator/pull/223

**Review by thomasmckay — CHANGES_REQUESTED** [review]
README.md deprecated

**Comment by drichtarik** [comment]
https://github.com/quay/quay-docs/pull/71
Should not the readme.md be updated to refer to the new documentation and say that it's deprecated for the time being while you decide how to edit the readme.md after?

**Comment by thomasmckay** [comment]
@drichtarik You caught us in the middle of the switch. Thanks for the contribution over in quay-docs!

**Pull request closed without merging**
