### PR TITLE
Add Quay Metrics service Port

### PR DESCRIPTION
**Pull request by JuozasA**
Since Prometheus Pushgateway is used for metrics and it can be accessed via port 9091, adding it to the Quay service.

P.S.
Exists in OCP templates as well: 
https://github.com/quay/quay/blob/e919361a9aad73df015c692e31a1fe1d015cafa4/deploy/openshift/quay-app.yaml#L62

### CODE REVIEW

**Comment by sabre1041** [comment]
@JuozasA would you be able to remove the `QuayRepoMirrorContainerPort` and instead just leverage any associated references to it using the new Prometheus variable you added?

**Comment by JuozasA** [comment]
> @JuozasA would you be able to remove the `QuayRepoMirrorContainerPort` and instead just leverage any associated references to it using the new Prometheus variable you added?

Sure. Is the quay-mirror using 9091? Assume quay/quay is a bit outdated... https://github.com/quay/quay/blob/master/deploy/k8s/quay-enterprise-mirror.yaml

**Comment by sabre1041** [comment]
@JuozasA it appears that you are building on top of your other PR. I would recommend that you use the latest `master`. I will be looking at #184 first

**Comment by sabre1041** [comment]
@JuozasA can you also add the `containerPort` to the Quay deployment as well?

**Comment by JuozasA** [comment]
> @JuozasA can you also add the `containerPort` to the Quay deployment as well?

Done

**Comment by sabre1041** [comment]
@JuozasA With #184 now merged to master. Can you rebase changes on top of master? We can get this resolved very quickly

**Comment by JuozasA** [comment]
> @JuozasA With #184 now merged to master. Can you rebase changes on top of master? We can get this resolved very quickly

Thanks! this one should be ok now

**Comment by sabre1041** [comment]
@JuozasA  doesnt appear to be properly rebased as it contains 26 commits instead of the expected 1.

**Comment by JuozasA** [comment]
Since it is 15 lines, I am closing this one and will open a new PR from the master branch instead... will be quicker

**Comment by sabre1041** [comment]
@JuozasA perfect. since it was a small change, this would be the easiest

**Pull request closed without merging**
