### PR TITLE
Bump operator version to v0.0.5

### PR DESCRIPTION
**Pull request by sabre1041**
Bump the version of the operator to v0.0.5

### CODE REVIEW

**Comment by sabre1041** [comment]
Awaiting confirmation of latest image for a resolution to #60

**Comment by wkulhanek** [comment]
/LGTM
Tested latest Operator tag with Quay 3.0.4. Deployed OK.

**Comment by sabre1041** [comment]
@thomasmckay @ibazulic should be good to go

**Review by ibazulic — APPROVED** [review]
Lgtm

**Pull request merged**
