### PR TITLE
Use latest Project Quay images

### PR DESCRIPTION
**Pull request by kurtismullins**
The latest upstream Project Quay images from the sprint `padme` are now available on quay.io. This Pull Request uses those images.

### CODE REVIEW

**Review by sabre1041 — APPROVED** [review]
@kurtismullins Tested successfully. Only question I have is whether we want to remove the explicit inclusions of the `imagePullSecret` from the documentation for the upstream operator?

**Comment by kurtismullins** [comment]
> @kurtismullins Tested successfully. Only question I have is whether we want to remove the explicit inclusions of the `imagePullSecret` from the documentation for the upstream operator?

Good question. I think it would be a good idea to make sure it's documented but it would be nice to simplify the sample CR and it might be more informative if we document it as its own setting.

I would back whatever decision you make here :)

**Comment by sabre1041** [comment]
@kurtismullins i would suggest that the docs here align with the expected functionality by default. if images do not require auth by default, remove from the examples. Of course, we would still want to show how it can be configured as we already currently do in the section on how to access protected images

**Review by sabre1041 — APPROVED** [review]
Will be merging to keep moving things forward. Followup PR to address documentation needs

**Pull request merged**
