### PR TITLE
bundle: regenerate CRDs

### PR DESCRIPTION
**Pull request by flavianmissi**
use:
```
  $ kustomize build config/crd > crds.yaml
```
to regenerate the crds, then open crds.yaml and copy/paste each crd to its
respective file in bundle/upstream.
downstream files are left as is. in a follow-up PR they'll be removed,
so I didn't bother updating them.

Relates to PROJQUAY-2690

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
@flavianmissi what version of kustomize are you using? The command you mentioned fails here for me:



```
$ kustomize build config/crd > crds.yaml
Error: accumulating resources: accumulation err='accumulating resources from 'bases/redhatcop.redhat.io.quay.redhat.com_quayecosystems.yaml': evalsymlink failure on '/home/rmarasch/go/src/github.com/quay/quay-operator/config/crd/bases/redhatcop.redhat.io.quay.redhat.com_quayecosystems.yaml' : lstat /home/rmarasch/go/src/github.com/quay/quay-operator/config/crd/bases/redhatcop.redhat.io.quay.redhat.com_quayecosystems.yaml: no such file or directory': evalsymlink failure on '/home/rmarasch/go/src/github.com/quay/quay-operator/config/crd/bases/redhatcop.redhat.io.quay.redhat.com_quayecosystems.yaml' : lstat /home/rmarasch/go/src/github.com/quay/quay-operator/config/crd/bases/redhatcop.redhat.io.quay.redhat.com_quayecosystems.yaml: no such file or directory
```

**Comment by flavianmissi** [comment]
@ricardomaraschini have you tried the command with the code in this PR? `config/crd/kustomization.yaml` on master points to `config/crd/bases/redhatcop.redhat.io.quay.redhat.com_quayecosystems.yaml`, which no longer exists.

**Comment by ricardomaraschini** [comment]
@flavianmissi Ahhhh, I completely misunderstood this PR. Nevermind.

**Review by ricardomaraschini — APPROVED** [review]

**Pull request merged**
