### PR TITLE
Added ingresses to quay-operator role

### PR DESCRIPTION
**Pull request by sabre1041**
Added ingresses to quay-operator role

### CODE REVIEW

**Comment by kurtismullins** [comment]
@sabre1041 Does this only affect manual installation of the operator? Does this change also need to be made to the CSV or anything else?

**Comment by sabre1041** [comment]
If you build the CSV using the `operator-sdk generate csv`, it will be sure to add the appropriate changes.

**Comment by kurtismullins** [comment]
> If you build the CSV using the `operator-sdk generate csv`, it will be sure to add the appropriate changes.

Ahh, great to know. Thank you!

**Review by kurtismullins — APPROVED** [review]
LGTM

**Pull request merged**
