### PR TITLE
pgmigration: fixing managed clair postgres migration error (PROJQUAY-8048)

### PR DESCRIPTION
**Pull request by deshpandevlab**
### Description

Clair and Quay postgres migrations were controlled by a single env variable. It was checking that the postgres version of new clair-postgres pods i.e postgres-15 was not matching the expected postgres version i.e. postgres-13. This retriggered the upgrade process making the postgres upgrade job stuck in the loop. 

This change separates the clair postgres migration component and rectify the logic of validating the upgrade job completion.

### Testing
- e2e tests
- manually validated push-pull 
- manually validated postgres versions

### CODE REVIEW

**Review by jonathankingfc — APPROVED** [review]
LGTM

**Comment by deshpandevlab** [comment]
``` 
oc get pod
NAME                                               READY   STATUS      RESTARTS      AGE
shubhra-registry-clair-app-9d8c5bf45-lhgzg         1/1     Running     1 (25m ago)   27m
shubhra-registry-clair-app-9d8c5bf45-v5kbw         1/1     Running     1 (25m ago)   27m
shubhra-registry-clair-postgres-5d6bb5bd9d-pjsbj   1/1     Running     0             25m
shubhra-registry-clair-postgres-upgrade-nvbh5      0/1     Completed   0             28m
shubhra-registry-quay-app-78d858df64-7sbjl         1/1     Running     0             7m9s
shubhra-registry-quay-app-78d858df64-tbk7t         1/1     Running     0             8m10s
shubhra-registry-quay-app-upgrade-gzhpq            0/1     Completed   0             77m
shubhra-registry-quay-database-647fc86fd7-5kl8c    1/1     Running     0             77m
shubhra-registry-quay-redis-d6d98bbfc-6qbn7        1/1     Running     0             8m41s
```

tested manually

**Pull request merged**
