### PR TITLE
Support for Additional Registry storage backends

### LINKED ISSUE #49: Add config options for various storage backends
Currently, we only support local storage backend for configuration, which is undesirable in production environments. We should add config support for other, cloud storage backends.

### PR DESCRIPTION
**Pull request by sabre1041**
Introduces additional registry storage options beyond local storage to resolve #49

### CODE REVIEW

**Comment by sabre1041** [comment]
The following are several configurations that can be used to test this PR:

**Azure:**

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    keepConfigDeployment: true
    registryBackends:
      - name: azure
        azure:
          azure_container: <container>
          azure_account_name: <account_name>
          azure_account_key: <account_key>
    imagePullSecretName: <pull secrert>
```

***AWS S3***

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    keepConfigDeployment: true
    registryBackends:
      - name: aws
        s3:
          s3_access_key: <access_key>
          s3_bucket: <bucket>
          s3_secret_key:<secret_key>
          host: <host>
    imagePullSecretName: <pull secrert>
```
**Replicated S3**

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    keepConfigDeployment: true
    enableStorageReplication: true
    registryBackends:
      - name: aws-1
        s3:
          s3_access_key: <access_key>
          s3_bucket: <bucket>
          s3_secret_key:<secret_key>
          host: <host>
          replicateByDefault: true
      - name: aws-2
        s3:
          s3_access_key: <access_key>
          s3_bucket: <bucket>
          s3_secret_key:<secret_key>
          host: <host>
          replicateByDefault: true
    imagePullSecretName: <pull secrert>
```

**Comment by sabre1041** [comment]
Extra CA Certificates can now be added using the following example

1. Create Secret containing CA certificate (example uses a certificate called extraca.crt)

```
oc create secret generic extracert1 --from-file=extraca.crt=<certificate_file>
```

Create the `QuayEcosystem` resource

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    keepConfigDeployment: true
    imagePullSecretName: redhat-pull-secret
    extraCaCerts:
      - secretName: extracert1
```

**Comment by sabre1041** [comment]
The `extraCaCerts` property has been reorganized. Here is an example of how to leverage new `configFiles` property in context to the Swift (OpenStack) registry backend

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    registryBackends:
      - name: swift
        swift:
          auth_url: <auth url>
          auth_version: <auth_version>
          ca_cert_path: "conf/stack/<filename_from_secret>"
          swift_password: <password>
          swift_user: <username>
          swift_container: <container>
          storage_path: /datastorage/registry
          os_options:
            object_storage_url: <object_storage_url>
            project_id: <project_id>
            user_domain_name: <user_domain_name>
    configFiles:
      - secretName: <secret>
  imagePullSecretName: redhat-quay-pull-secret
```

**Comment by sabre1041** [comment]
@thomasmckay this is ready for review and merge

**Review by kurtismullins — APPROVED** [review]
LGTM - I did not have the time and resources to verify every backend you have introduced but as far as I can tell it should work as expected.

**Pull request merged**
