### PR TITLE
Removed e2e from pull_request

### PR DESCRIPTION
**Pull request by ricardomaraschini**
We need to address this somehow but for now let's keep this as a nightly
job only thing.

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
@flavianmissi would you mind checking if this is right ?

**Review by flavianmissi — DISMISSED** [review]
Is the intention to run the `make test-e2e` on the e2e nightly workflow on a follow-up PR?
If that's the case, then this one LGTM.

**Comment by ricardomaraschini** [comment]
> Is the intention to run the `make test-e2e` on the e2e nightly workflow on a follow-up PR? If that's the case, then this one LGTM.

@flavianmissi I thought it was already enabled for nightly builds. Added, PTAL.

**Review by flavianmissi — APPROVED** [review]
🚀

**Pull request merged**
